### ISSUE TITLE
Capable of backing a web api for autocomplete 

### ISSUE THREAD

**Issue by nhaberl** [wolfgarbe/PruningRadixTrie#1]
Would have the need of an autocomplete functionality which can handle thousands of words of a given domain within a website.

So my question is if I can use your data structure in a website with high concurrency and if its writable or read only ?

Its awesome what you have done here, the only place where I found something similar is CQEngine in Java, which has also special Trie structure for prefix searches...and is build for concurre cy in mind.

**Comment by wolfgarbe** [comment]
I'm using the PrunngRadixTrie in a search engine with high concurrency. It is writable - with AddTerm I build the auto-complete dictionary incrementally from scratch during indexing with the search engine.

AddTerm and GetTopkTermsForPrefix have to be synchronized with Lock.

While you could use a simple Lock(), a ReaderWriterLockSlim ensures better performance, because it still allows multiple Lookups in parallel:
```
threadLock.EnterReadLock();
try
{
      pruningRadixTrie.GetTopkTermsForPrefix(String prefix, int topK, out long count);
}
finally
{
      threadLock.ExitReadLock();
}

threadLock.EnterWriteLock();
try
{
    pruningRadixTrie.AddTerm(String term, long termFrequencyCount);
}
finally
{
    threadLock.ExitWriteLock();
}
```

**Comment by nhaberl** [comment]
Thanks a lot!
If I add the same term more often, do the statistics get updated or do I have to set the right frequency term on any Add()?

Because I have not 100 % of lookup values when starting...it grows over time.

**Comment by wolfgarbe** [comment]
[The statistics get updated every time you add the same term](https://github.com/wolfgarbe/PruningRadixTrie/blob/master/PruningRadixTrie/Program.cs#L77).

But the new count is added to the existing count (the existing count is NOT replaced with the new count).

**Comment by nhaberl** [comment]
Makes sense, so its incremental.
Is there a way to set a weight or anything or is the ranking always based on frequency?

Just in case anything less common is more important maybe.

**Comment by wolfgarbe** [comment]
termFrequencyCount is just a 64 bit integer. You can use it however it fits your requirements. So it can be a price to have expensive products on top, an age to sell old products first, it can be a query frequency (rare word in index, but often searched by user) etc. You are completely free to define your own ranking. The candidates matching the prefix are sorted by this number, in descending order. Its up to you to define what this number means.

**Comment by nhaberl** [comment]
In that case it would be great to have an api for updating the int value for a term otherwise there is no chance for adjustment other than recreating the whole Trie.

With only frequency in mind the API is perfect but with possible individual score its a bit narrow to set custom "rank" or "push" some values to a given position.

**Comment by wolfgarbe** [comment]
In addition to AddTerm() I could provide a SetTerm() to just set the rank to a certain value.

But in the meantime you can achieve the same, as AddTerm() allows for negative values.
So you could do something like AddTerm("term", new_value-old_value)

**Comment by nhaberl** [comment]
Nice idea for short term
Appreciate a separate method too.

Thanks again
