### ISSUE TITLE
Memory consumption

### ISSUE THREAD

**Issue by nhaberl** [wolfgarbe/PruningRadixTrie#3]
Is there any way to calculate memory based on given terms ?

**Comment by wolfgarbe** [comment]
You mean calculating the memory consumption of the trie **before** it is created? I don't think so, because it depends on the actual terms how compressible (shared prefixes of terms) they are. You can calculate only the worst case.

**Comment by nhaberl** [comment]
Yes right, just to prevent scaling issues.
Or are there any other things to consider when filling up with terms.
As I know the query times should be almost constant.

**Comment by wolfgarbe** [comment]
To prevent scaling issues when incrementally building the trie, you can just count the nodes. When the number of nodes reaches a certain limit, you either stop updating the trie (the most frequent/most relevant terms are usually are added early) or you remove terms (this is not yet implemented) with low word count to free space.
