### ISSUE TITLE
I have ported to Java. Reference in the README?

### ISSUE THREAD

**Issue by benldr** [wolfgarbe/PruningRadixTrie#8]
Hi Mr Garbe,  

Thanks for your brilliant work! I have ported the source code to Java, and put it in [benldr/JPruningRadixTrie](https://github.com/benldr/JPruningRadixTrie).  You might like to reference this in your readme, so that any other Java users can avoid having to port the code themselves?

I have tested it and seems to work as desired (in any case, I will be actively using this code in months to come so will become aware of any bugs if there are any). Note I did not port the *PruningRadixTrie.Benchmark* code.   

Thanks again for your great work,
Ben

**Comment by wolfgarbe** [comment]
Thanks for your port. I have linked it in the Readme of my PruningRadixTrie repository: https://github.com/wolfgarbe/PruningRadixTrie/blob/master/README.md#ports

Wolf
