### ISSUE TITLE
Terms.txt

### ISSUE THREAD

**Issue by hp4k1h5** [wolfgarbe/PruningRadixTrie#9]
I believe this file https://github.com/wolfgarbe/PruningRadixTrie/blob/master/PruningRadixTrie/terms.zip , referenced in the Readme is missing.
<img width="492" alt="Screenshot 2023-09-30 at 08 42 55" src="https://github.com/wolfgarbe/PruningRadixTrie/assets/20137484/505d29bf-a34d-440e-a863-fd510315c8dd">

**Comment by wolfgarbe** [comment]
Thank you. The link has just been updated to https://github.com/wolfgarbe/PruningRadixTrie/blob/master/PruningRadixTrie.Benchmark/terms.zip

**Comment by adi-kmt** [comment]
Hey @wolfgarbe how are the scores/rank value in this txt file calculated?

**Comment by wolfgarbe** [comment]
Terms.txt contains 6 million unigrams and bigrams derived from English Wikipedia titles, with the term frequency counts used for ranking. Stopwords and numbers were ignored. The term frequency (TF) of a term within all Wikipedia titles is used as score for ranking the suggestion. In the suggestion list will be those terms/term combination (bigrams) with the highest term frequency ranked on top.

The used algorithm to create the  terms.txt dictionary is not very sophisticated. There is certainly room for improvement. It merely serves as demonstration for the pruning radix tree algorithm. You could extend this to n-grams, or use frequencies from [Google Books n-gram data](https://storage.googleapis.com/books/ngrams/books/datasetsv2.html)
